// This file is auto-generated by tauri-specta. Do not edit manually.
// Run `cargo build` (debug) or `cargo test export_bindings` to regenerate.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	// Creates a new PTY session and returns its unique ID.
	ptyCreate: (config: SessionConfig) => typedError<string, AppError>(__TAURI_INVOKE("pty_create", { config })),
	// Sends raw bytes (user keystrokes) to the PTY.
	ptyWrite: (sessionId: string, data: number[]) => typedError<null, AppError>(__TAURI_INVOKE("pty_write", { sessionId, data })),
	// Notifies the PTY of a terminal window resize.
	ptyResize: (sessionId: string, rows: number, cols: number) => typedError<null, AppError>(__TAURI_INVOKE("pty_resize", { sessionId, rows, cols })),
	// Closes the PTY session and kills the shell process.
	ptyClose: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("pty_close", { sessionId })),
	// Returns metadata for all currently active sessions.
	ptyListActive: () => typedError<SessionInfo[], AppError>(__TAURI_INVOKE("pty_list_active")),
	// Returns the platform-default shell path (e.g. `/bin/zsh` on macOS).
	ptyDefaultShell: () => __TAURI_INVOKE<string>("pty_default_shell"),
	// Returns the current application configuration.
	configGet: () => typedError<AppConfig, AppError>(__TAURI_INVOKE("config_get")),
	// Persists a new configuration (replaces the current one).
	configSet: (config: AppConfig) => typedError<null, AppError>(__TAURI_INVOKE("config_set", { config })),
};

/* Types */
export type AiConfig = {
	provider: AiProvider,
	model: string,
	// API key. Empty string means read from environment variable.
	apiKey: string,
	ollamaBaseUrl: string,
	defaultMode: AiMode,
};

export type AiMode = 
// AI only suggests; user executes manually.
"suggest" | 
// AI can run read-only commands automatically.
"assist" | 
// AI can run write commands with per-command confirmation.
"agent" | 
// AI runs everything; all actions are audit-logged.
"fullAuto";

export type AiProvider = "openai" | "anthropic" | "ollama";

export type AppConfig = {
	appearance?: AppearanceConfig,
	shell?: ShellConfig,
	ai?: AiConfig,
};

/**
 *  Unified application error type.
 *  All variants implement Serialize so they can be returned from Tauri commands.
 */
export type AppError = { kind: "Pty"; message: string } | { kind: "SessionNotFound"; message: string } | { kind: "Io"; message: string } | { kind: "Config"; message: string } | { kind: "Database"; message: string } | { kind: "AiProvider"; message: string };

export type AppearanceConfig = {
	theme: Theme,
	fontFamily: string,
	fontSize: number,
	opacity: number,
};

// Configuration for a local shell session.
export type LocalShellConfig = {
	// Path to the shell executable.
	shell: string,
	// Arguments passed to the shell (e.g. `["--login"]`).
	args: string[],
	// Extra environment variables.
	env: { [key in string]: string },
	// Initial working directory. `None` uses the user's home directory.
	cwd: string | null,
};

// Session configuration variants (local shell for now; SSH to follow in Phase 2).
export type SessionConfig = { type: "local" } & (LocalShellConfig);

// Metadata about an active PTY session returned to the frontend.
export type SessionInfo = {
	id: string,
	title: string,
	startedAt: string,
};

export type ShellConfig = {
	/**
	 *  Path to the default shell executable.
	 *  None means auto-detect on each platform.
	 */
	defaultShell: string | null,
	// Extra arguments to pass to the shell.
	args: string[],
	// Extra environment variables to inject into new sessions.
	env: { [key in string]: string },
};

export type Theme = "dark" | "light" | "system";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

