pub mod commands;
pub mod config;
pub mod error;
pub mod pty;
pub mod state;

use commands::config::{config_get, config_set};
use commands::pty::{
    pty_close, pty_create, pty_default_shell, pty_list_active, pty_resize, pty_write,
};
use state::AppState;
use tauri_specta::{collect_commands, Builder};

/// Builds the specta command registry (shared between `run()` and tests).
fn make_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        pty_create,
        pty_write,
        pty_resize,
        pty_close,
        pty_list_active,
        pty_default_shell,
        config_get,
        config_set,
    ])
}

/// Exports TypeScript bindings to `src/types/bindings.ts`.
/// Called at app startup in debug builds, and available as a test helper.
pub fn export_bindings() {
    make_builder()
        .export(
            specta_typescript::Typescript::default()
                .header("// This file is auto-generated by tauri-specta. Do not edit manually.\n// Run `cargo build` (debug) or `cargo test export_bindings` to regenerate.\n"),
            "../src/types/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = make_builder();

    #[cfg(debug_assertions)]
    export_bindings();

    let config = config::ConfigManager::load().unwrap_or_default();
    let app_state = AppState::new(config);

    tauri::Builder::default()
        .manage(app_state)
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            Ok(())
        })
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

// ── D3: bindings export test ──────────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;

    /// Exports bindings to `src/types/bindings.ts` and verifies the file
    /// contains all expected Tauri command names and key types.
    #[test]
    fn bindings_contain_expected_symbols() {
        // This also regenerates the file on every test run in debug mode.
        export_bindings();

        let contents = std::fs::read_to_string("../src/types/bindings.ts")
            .expect("bindings.ts should exist after export");

        for symbol in &[
            "ptyCreate",
            "ptyWrite",
            "ptyResize",
            "ptyClose",
            "ptyListActive",
            "configGet",
            "configSet",
            "SessionConfig",
            "LocalShellConfig",
            "SessionInfo",
            "AppConfig",
            "AppError",
        ] {
            assert!(
                contents.contains(symbol),
                "bindings.ts missing symbol: {symbol}"
            );
        }
    }
}
